name: Jike Info Collector Task

on:
  schedule:
    # 北京时间8点到24点每半个小时执行一次爬取任务
    # 北京时间8点=UTC0点，北京时间24点=UTC16点
    - cron: '0,30 0-16 * * *'
    # 每天北京时间8点运行清理任务（UTC时间0点）
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      task:
        description: '要手动执行的任务'
        required: true
        default: 'crawl'
        type: choice
        options:
        - crawl
        - cleanup
        - stats
        - full

jobs:
  crawl:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0,30 0-16 * * *' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'crawl' || github.event.inputs.task == 'full'))
    env:
      # --- 数据库密钥 ---
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSL_MODE: ${{ secrets.DB_SSL_MODE }}
      # --- 爬虫配置 (可选) ---
      EXECUTOR_MAX_WORKERS: ${{ secrets.EXECUTOR_MAX_WORKERS }}
      CRAWLER_REQUEST_TIMEOUT: ${{ secrets.CRAWLER_REQUEST_TIMEOUT }}
      CRAWLER_MAX_RETRIES: ${{ secrets.CRAWLER_MAX_RETRIES }}
      RSSHUB_HOSTS: ${{ secrets.RSSHUB_HOSTS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run jike crawler
      run: python main.py --task crawl

  cleanup:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * *' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'cleanup' || github.event.inputs.task == 'full'))
    env:
      # --- 数据库密钥 ---
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSL_MODE: ${{ secrets.DB_SSL_MODE }}
      # --- 数据保留配置 (可选) ---
      DATA_RETENTION_DAYS: ${{ secrets.DATA_RETENTION_DAYS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run cleanup
      run: python main.py --task cleanup

  stats:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * *' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'stats' || github.event.inputs.task == 'full'))
    env:
      # --- 数据库密钥 ---
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSL_MODE: ${{ secrets.DB_SSL_MODE }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Get stats
      run: python main.py --task stats

  full:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'full'
    env:
      # --- 数据库密钥 ---
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSL_MODE: ${{ secrets.DB_SSL_MODE }}
      # --- 爬虫配置 (可选) ---
      EXECUTOR_MAX_WORKERS: ${{ secrets.EXECUTOR_MAX_WORKERS }}
      CRAWLER_REQUEST_TIMEOUT: ${{ secrets.CRAWLER_REQUEST_TIMEOUT }}
      CRAWLER_MAX_RETRIES: ${{ secrets.CRAWLER_MAX_RETRIES }}
      RSSHUB_HOSTS: ${{ secrets.RSSHUB_HOSTS }}
      DATA_RETENTION_DAYS: ${{ secrets.DATA_RETENTION_DAYS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run full task sequence
      run: python main.py --task full